server:
  port: ${PORT:8080}

spring:
  application:
    name: ${NAME:APP}
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

  pattern:
    level: "[trace: %X{traceId}][%5p]"

upstream:
  url: ${SERVICE_URL:#{null}}
